version: '3.7'
services:
#  docker-mysql:
#    image: mysql:latest
#    environment:
#      - MYSQL_ROOT_PASSWORD=Dobri2001
#      - MYSQL_DATABASE=musicplayer
#      - MYSQL_PASSWORD=Dobri2001

  docker-mysql:
    image: mysql:latest
    user: root
    volumes:
      - type: bind
        source: C:\ProgramData\MySQL\MySQL Server 8.0\Data\musicplayer
        target: /var/lib/mysql/:rw
    container_name: docker-mysql
    environment:
      - MYSQL_PASSWORD=Dobri2001
      - MYSQL_ALLOW_EMPTY_PASSWORD

  spring-boot-jpa-docker-webapp:
    image: player
    depends_on:
      - docker-mysql
    ports:
      - "8081:8080"
    environment:
      - DATABASE_HOST=docker-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=Dobri2001
      - DATABASE_NAME=musicplayer
      - DATABASE_PORT=3306

volumes:
  sqldata:





#version: '3.7'
#services:
#  db:
#    container_name: db
#    volumes:
#          - type: bind
#            source: C:\ProgramData\MySQL\MySQL Server 8.0\Data\musicplayer
#            target: /var/lib/mysql/
#    image: mysql:latest
#    environment:
#      MYSQL_ROOT_PASSWORD: Dobri2001
#      MYSQL_DATABASE: musicplayer
#    ports:
#      - "3307:3306"
#    networks:
#      - my-network
#
#  my-account-microservice:
#    container_name: my-account-microservice
#    image: my-account-microservice
#    build:
#      context: ./account-microservice
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://my-account-microservice-db:3307/musicplayer
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: Dobri2001
#      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
#      # SPRING.DATASOURCE.URL: jdbc:mysql://my-account-microservice-db:3307/my-account
#      # SPRING.DATASOURCE.USERNAME: root
#      # SPRING.DATASOURCE.PASSWORD: password
#      # SPRING.DATASOURCE.DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
#      # DATABASE_HOST: my-account-microservice-db
#      # DATABASE_USER: root
#      # DATABASE_PASSWORD: password
#      # DATABASE_PORT: 3307
#    depends_on:
#      - my-account-microservice-db
#    ports:
#      - "8090:8090"
#    networks:
#      - my-network
##    links:
##      - my-account-microservice-db:database
#
#networks:
#  my-network:


